StorageFlow manuals

1 Essentials
2 StorageFlow
3 Startup Configuration
4 Users Management
5 Storage Management
6 Reports
7 Help
8 About

-------------------------------------------------------------------------------
Essentials
   What StorageFlow can do for you
   But what it cannot do
   First steps
      Login
      Startup Configuration
      Basic storage Management
      Reports

-------------------------------------------------------------------------------
StorageFlow
   Login
      Language button
      User Name
      Remember me
      Password
         Display in plain text
         Entrering a password
         Hint
         Exit button
   Main Dashboard
      Colour Mode
      Language button
      Startup Configuration
      Users Management
      Storage Management
      Reports
      Help
      About
      Status bar
      Exit button

-------------------------------------------------------------------------------
Startup Configuration
   Language button
   Full user name
   Login name
   Password
   Password hint
   Language
   Note
   Save button
   Exit button

-------------------------------------------------------------------------------
Users Management
   New button
   Language button
   User ID
   Full user name
   Login name
   Password
   Password hint
   Language
   Note
   Role
   Datagrid
   Delete button
   Save button
   Exit button

-------------------------------------------------------------------------------
Storage Management
   New transaction button
   Save transaction button
   Language button
   Clients tab
      Client #
      Title
      First Name
      Last Name
      Address
      City
      Province
      Postal code
      Phone
         Home
         Mobile
         Other
         Comment
      Email
      Communications
         Language
         Emergency
         Prefered
      Note
      Stamps
         Creation
         Last Edit
      Clear button
      Destroy button
      Save button
      Clear button
      Clients Datagrid
      Units Datagrid
      Storages Datagrid
      Exit button
   Units tab
      Unit #
      Registration
      Unit Type
      Make
      Model
      Colour
      Length
      Propultion
      Propane
      Condition
      Special Request
      Note
      Stamps
         Creation
         Last Edit
      Clear button
      Destroy button
      Save button
      Clients Datagrid
      Clear button
      Units Datagrid
      Storages Datagrid
      Exit button
   Storages tab
      Storage #
      Dates
         Date In
         Date Out
         Season
      Payment
         Price before taxes
         GST
            Rate
            Amount
         PST
            Rate
            Amount
         Price taxes included
         Mode
         Date
      Location
         Building
         Position
      Note
      Stamps
         Creation
         Last Edit
      Clear button
      Destroy button
      Save button
      Clients Datagrid
      Units Datagrid
      Clear button
      Storages Datagrid
      Exit button

-------------------------------------------------------------------------------
Reports
   Language button
   Reports List
   Format
   Generate button
   Exit button

-------------------------------------------------------------------------------
Help

-------------------------------------------------------------------------------
About

-------------------------------------------------------------------------------
